# include dank-tabs.conf   # 该主题文件未纳入本次转换，已注释，避免 kitty 因缺失 include 启动失败
# include dank-theme.conf  # 同上
window_padding_width 5
hide_window_decorations yes
background_opacity 0.8
font_family JetBrains Maple Mono 
font_size 13.5
remember_window_size no
confirm_os_window_close 0
shell fish
cursor_trail 1 
cursor_shape block
shell_integration no-cursor



# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
