## mpv属性记录脚本配置：

# 退出时保存状态，下次启动时恢复
save_and_load=yes

# 内置属性（用逗号分隔）：
props=gpu-api,hwdec,ytdl-format,scale,dscale,scale-antiring,dscale-antiring,deband,target-colorspace-hint
# 可用的内置属性参考：https://mpv.io/manual/master/#property-list

# 自定义属性（用逗号分隔）：
user_props=thumbfast-off,thumbfast-hw-off,shaders,vs,nv-vsr,nv-hdr,ssdm-enabled,itm
# 可用自定义属性：
#   thumbfast-off：禁用略缩图功能
#   thumbfast-hw-off：禁用略缩图硬件解码
#   shaders：着色器
#   vs：VS
#   nv-vsr：NV-VSR
#   nv-hdr: NV-HDR
#   ssdm-enabled：弹幕形式（次字幕/OSD）
#   ssdm-pad：自动填充黑边
#   opencc-mode：字幕繁简转换模式
#   chap-skip：自动跳过设定章节
#   itm：HDR逆色调映射