## 功能增强脚本配置：

# 长按加速倍率
speed=2
# 是否开启混合快进加速
press_speed=no
# 按住加速时是否清除着色器
clear_glsl=no
# 按住加速是否临时关闭VS
speed_vs_off=no
# 跳转时是否临时关闭VS
seek_vs_off=no
# 自动跳过的章节名
skip_chapters=OP,ED,op,ed,opening,ending,Opening,Ending,オープニング,エンディング