## 弹幕脚本配置：

# 指定弹幕服务器地址，自定义服务需兼容 dandanplay 的 api
api_server=https://api.dandanplay.net
# 指定 b 站和爱腾优的弹幕获取的兜底服务器地址，主要用于获取非动画弹幕
# 服务器可以自托管：https://github.com/lyz05/danmaku
fallback_server=https://api.danmu.icu
# 设置 tmdb 的 API Key，用于获取非动画条目的中文信息(当搜索内容非中文时)
# 注意：自定义此参数时还需要对获取到的 API Key 进行 base64 编码
tmdb_api_key=NmJmYjIxOTZkNzIyN2UyMTIzMGM3Y2YzZjQ4MDNkZGM=

# 是否自动加载弹幕
auto_load=yes
# 是否自动加载本地弹幕
autoload_local_danmaku=yes
# 是否为 URL 自动加载弹幕
autoload_for_url=yes
# 是否文件结束时自动保存弹幕
save_danmaku=no

# 用户代理
user_agent=mpv_danmaku/1.0
# 代理设置
proxy=
# 使用 fps 视频滤镜，大幅提升弹幕平滑度
vf_fps=no
# 设置要使用的 fps 滤镜参数
fps=60/1.001
# 合并重复弹幕的时间间隔容差（秒），-1 表示禁用
merge_tolerance=-1
# 弹幕关联历史记录文件路径
history_path=~~/danmaku-history.json
# 打开搜索弹幕菜单的快捷键
open_search_danmaku_menu_key=
# 显示弹幕键盘快捷键
show_danmaku_keyboard_key=

# 中文简繁转换：0-不转换，1-简体，2-繁体
chConvert=0
# 滚动弹幕显示时间
scrolltime=15
# 固定弹幕显示时间
fixtime=5

# 字体
fontname=SimHei
# 字体大小
fontsize=32
# 字体阴影
shadow=0
# 字体粗体
bold=yes
# 透明度：0（完全透明）到 1（不透明）
opacity=0.75
# 弹幕显示范围（0.0-1.0）
displayarea=0.25
# 描边 0-4
outline=1.0

# 最大同时显示弹幕数量，0 表示不限制
max_screen_danmaku=0
# 弹幕屏蔽词文件路径
blacklist_path=
# 脚本消息对齐方式
message_anlignment=7
# 脚本消息 X 坐标
message_x=20
# 脚本消息 Y 坐标
message_y=80
# 自定义标题解析替换规则（JSON 格式）
title_replace=[{ "rules": [{ "^〔(.-)〕": "%1"},{ "^.*《(.-)》": "%1" }] }]
# 哈希匹配中忽略的共享盘路径（JSON 数组格式）
excluded_path=[]